blank_issues_enabled: false
contact_links:
  - name: Request a new feature
    url: https://github.com/LaWebcapsule/d9/discussions/new?category=feature-requests
    about: Share your ideas on how to make d9 better.
  - name: Suggest improvements for the docs
    url: https://github.com/LaWebcapsule/d9/discussions/new?category=docs-suggestions
    about: Share your ideas on how to improve the documentation of d9.
  - name: Ask a question
    url: https://github.com/LaWebcapsule/d9/discussions
    about: Please ask and answer questions here.
